// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MAIN_MOE_NET_H_
#define FLATBUFFERS_GENERATED_MAIN_MOE_NET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "Events_generated.h"
#include "PlayerUpdate_generated.h"
#include "Weapon_generated.h"

namespace moe {
namespace net {

struct ReceivedHeader;
struct ReceivedHeaderBuilder;

struct ReceivedNetMessage;
struct ReceivedNetMessageBuilder;

enum ReceivedPacketUnion : uint8_t {
  ReceivedPacketUnion_NONE = 0,
  ReceivedPacketUnion_AllPlayerUpdate = 1,
  ReceivedPacketUnion_GameEvent = 2,
  ReceivedPacketUnion_MIN = ReceivedPacketUnion_NONE,
  ReceivedPacketUnion_MAX = ReceivedPacketUnion_GameEvent
};

inline const ReceivedPacketUnion (&EnumValuesReceivedPacketUnion())[3] {
  static const ReceivedPacketUnion values[] = {
    ReceivedPacketUnion_NONE,
    ReceivedPacketUnion_AllPlayerUpdate,
    ReceivedPacketUnion_GameEvent
  };
  return values;
}

inline const char * const *EnumNamesReceivedPacketUnion() {
  static const char * const names[4] = {
    "NONE",
    "AllPlayerUpdate",
    "GameEvent",
    nullptr
  };
  return names;
}

inline const char *EnumNameReceivedPacketUnion(ReceivedPacketUnion e) {
  if (::flatbuffers::IsOutRange(e, ReceivedPacketUnion_NONE, ReceivedPacketUnion_GameEvent)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesReceivedPacketUnion()[index];
}

template<typename T> struct ReceivedPacketUnionTraits {
  static const ReceivedPacketUnion enum_value = ReceivedPacketUnion_NONE;
};

template<> struct ReceivedPacketUnionTraits<moe::net::AllPlayerUpdate> {
  static const ReceivedPacketUnion enum_value = ReceivedPacketUnion_AllPlayerUpdate;
};

template<> struct ReceivedPacketUnionTraits<moe::net::GameEvent> {
  static const ReceivedPacketUnion enum_value = ReceivedPacketUnion_GameEvent;
};

bool VerifyReceivedPacketUnion(::flatbuffers::Verifier &verifier, const void *obj, ReceivedPacketUnion type);
bool VerifyReceivedPacketUnionVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct ReceivedHeader FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ReceivedHeaderBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SERVERTICK = 4,
    VT_SERVERTSMS = 6
  };
  uint64_t serverTick() const {
    return GetField<uint64_t>(VT_SERVERTICK, 0);
  }
  uint64_t serverTsMs() const {
    return GetField<uint64_t>(VT_SERVERTSMS, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_SERVERTICK, 8) &&
           VerifyField<uint64_t>(verifier, VT_SERVERTSMS, 8) &&
           verifier.EndTable();
  }
};

struct ReceivedHeaderBuilder {
  typedef ReceivedHeader Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_serverTick(uint64_t serverTick) {
    fbb_.AddElement<uint64_t>(ReceivedHeader::VT_SERVERTICK, serverTick, 0);
  }
  void add_serverTsMs(uint64_t serverTsMs) {
    fbb_.AddElement<uint64_t>(ReceivedHeader::VT_SERVERTSMS, serverTsMs, 0);
  }
  explicit ReceivedHeaderBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ReceivedHeader> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ReceivedHeader>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ReceivedHeader> CreateReceivedHeader(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t serverTick = 0,
    uint64_t serverTsMs = 0) {
  ReceivedHeaderBuilder builder_(_fbb);
  builder_.add_serverTsMs(serverTsMs);
  builder_.add_serverTick(serverTick);
  return builder_.Finish();
}

struct ReceivedNetMessage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ReceivedNetMessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HEADER = 4,
    VT_PACKET_TYPE = 6,
    VT_PACKET = 8
  };
  const moe::net::ReceivedHeader *header() const {
    return GetPointer<const moe::net::ReceivedHeader *>(VT_HEADER);
  }
  moe::net::ReceivedPacketUnion packet_type() const {
    return static_cast<moe::net::ReceivedPacketUnion>(GetField<uint8_t>(VT_PACKET_TYPE, 0));
  }
  const void *packet() const {
    return GetPointer<const void *>(VT_PACKET);
  }
  template<typename T> const T *packet_as() const;
  const moe::net::AllPlayerUpdate *packet_as_AllPlayerUpdate() const {
    return packet_type() == moe::net::ReceivedPacketUnion_AllPlayerUpdate ? static_cast<const moe::net::AllPlayerUpdate *>(packet()) : nullptr;
  }
  const moe::net::GameEvent *packet_as_GameEvent() const {
    return packet_type() == moe::net::ReceivedPacketUnion_GameEvent ? static_cast<const moe::net::GameEvent *>(packet()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_HEADER) &&
           verifier.VerifyTable(header()) &&
           VerifyField<uint8_t>(verifier, VT_PACKET_TYPE, 1) &&
           VerifyOffset(verifier, VT_PACKET) &&
           VerifyReceivedPacketUnion(verifier, packet(), packet_type()) &&
           verifier.EndTable();
  }
};

template<> inline const moe::net::AllPlayerUpdate *ReceivedNetMessage::packet_as<moe::net::AllPlayerUpdate>() const {
  return packet_as_AllPlayerUpdate();
}

template<> inline const moe::net::GameEvent *ReceivedNetMessage::packet_as<moe::net::GameEvent>() const {
  return packet_as_GameEvent();
}

struct ReceivedNetMessageBuilder {
  typedef ReceivedNetMessage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_header(::flatbuffers::Offset<moe::net::ReceivedHeader> header) {
    fbb_.AddOffset(ReceivedNetMessage::VT_HEADER, header);
  }
  void add_packet_type(moe::net::ReceivedPacketUnion packet_type) {
    fbb_.AddElement<uint8_t>(ReceivedNetMessage::VT_PACKET_TYPE, static_cast<uint8_t>(packet_type), 0);
  }
  void add_packet(::flatbuffers::Offset<void> packet) {
    fbb_.AddOffset(ReceivedNetMessage::VT_PACKET, packet);
  }
  explicit ReceivedNetMessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ReceivedNetMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ReceivedNetMessage>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ReceivedNetMessage> CreateReceivedNetMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<moe::net::ReceivedHeader> header = 0,
    moe::net::ReceivedPacketUnion packet_type = moe::net::ReceivedPacketUnion_NONE,
    ::flatbuffers::Offset<void> packet = 0) {
  ReceivedNetMessageBuilder builder_(_fbb);
  builder_.add_packet(packet);
  builder_.add_header(header);
  builder_.add_packet_type(packet_type);
  return builder_.Finish();
}

inline bool VerifyReceivedPacketUnion(::flatbuffers::Verifier &verifier, const void *obj, ReceivedPacketUnion type) {
  switch (type) {
    case ReceivedPacketUnion_NONE: {
      return true;
    }
    case ReceivedPacketUnion_AllPlayerUpdate: {
      auto ptr = reinterpret_cast<const moe::net::AllPlayerUpdate *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ReceivedPacketUnion_GameEvent: {
      auto ptr = reinterpret_cast<const moe::net::GameEvent *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyReceivedPacketUnionVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyReceivedPacketUnion(
        verifier,  values->Get(i), types->GetEnum<ReceivedPacketUnion>(i))) {
      return false;
    }
  }
  return true;
}

inline const moe::net::ReceivedNetMessage *GetReceivedNetMessage(const void *buf) {
  return ::flatbuffers::GetRoot<moe::net::ReceivedNetMessage>(buf);
}

inline const moe::net::ReceivedNetMessage *GetSizePrefixedReceivedNetMessage(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<moe::net::ReceivedNetMessage>(buf);
}

inline bool VerifyReceivedNetMessageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<moe::net::ReceivedNetMessage>(nullptr);
}

inline bool VerifySizePrefixedReceivedNetMessageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<moe::net::ReceivedNetMessage>(nullptr);
}

inline void FinishReceivedNetMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<moe::net::ReceivedNetMessage> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedReceivedNetMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<moe::net::ReceivedNetMessage> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace net
}  // namespace moe

#endif  // FLATBUFFERS_GENERATED_MAIN_MOE_NET_H_
