// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PLAYERTEAM_MOE_NET_H_
#define FLATBUFFERS_GENERATED_PLAYERTEAM_MOE_NET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace moe {
namespace net {

enum PlayerTeam : int8_t {
  PlayerTeam_TEAM_NONE = 0,
  PlayerTeam_TEAM_T = 1,
  PlayerTeam_TEAM_CT = 2,
  PlayerTeam_MIN = PlayerTeam_TEAM_NONE,
  PlayerTeam_MAX = PlayerTeam_TEAM_CT
};

inline const PlayerTeam (&EnumValuesPlayerTeam())[3] {
  static const PlayerTeam values[] = {
    PlayerTeam_TEAM_NONE,
    PlayerTeam_TEAM_T,
    PlayerTeam_TEAM_CT
  };
  return values;
}

inline const char * const *EnumNamesPlayerTeam() {
  static const char * const names[4] = {
    "TEAM_NONE",
    "TEAM_T",
    "TEAM_CT",
    nullptr
  };
  return names;
}

inline const char *EnumNamePlayerTeam(PlayerTeam e) {
  if (::flatbuffers::IsOutRange(e, PlayerTeam_TEAM_NONE, PlayerTeam_TEAM_CT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPlayerTeam()[index];
}

}  // namespace net
}  // namespace moe

#endif  // FLATBUFFERS_GENERATED_PLAYERTEAM_MOE_NET_H_
