// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PLAYERUPDATE_MOE_NET_H_
#define FLATBUFFERS_GENERATED_PLAYERUPDATE_MOE_NET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "Weapon_generated.h"

namespace moe {
namespace net {

struct Vec3;

struct PlayerUpdate;
struct PlayerUpdateBuilder;

struct AllPlayerUpdate;
struct AllPlayerUpdateBuilder;

enum PlayerMotionState : int8_t {
  PlayerMotionState_NORMAL = 0,
  PlayerMotionState_JUMPING = 1,
  PlayerMotionState_CROUCHING = 2,
  PlayerMotionState_MIN = PlayerMotionState_NORMAL,
  PlayerMotionState_MAX = PlayerMotionState_CROUCHING
};

inline const PlayerMotionState (&EnumValuesPlayerMotionState())[3] {
  static const PlayerMotionState values[] = {
    PlayerMotionState_NORMAL,
    PlayerMotionState_JUMPING,
    PlayerMotionState_CROUCHING
  };
  return values;
}

inline const char * const *EnumNamesPlayerMotionState() {
  static const char * const names[4] = {
    "NORMAL",
    "JUMPING",
    "CROUCHING",
    nullptr
  };
  return names;
}

inline const char *EnumNamePlayerMotionState(PlayerMotionState e) {
  if (::flatbuffers::IsOutRange(e, PlayerMotionState_NORMAL, PlayerMotionState_CROUCHING)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPlayerMotionState()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

struct PlayerUpdate FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PlayerUpdateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TEMPID = 4,
    VT_POS = 6,
    VT_VEL = 8,
    VT_HEAD = 10,
    VT_MOTIONSTATE = 12,
    VT_WEAPON = 14,
    VT_HEALTH = 16
  };
  uint16_t tempId() const {
    return GetField<uint16_t>(VT_TEMPID, 0);
  }
  const moe::net::Vec3 *pos() const {
    return GetStruct<const moe::net::Vec3 *>(VT_POS);
  }
  const moe::net::Vec3 *vel() const {
    return GetStruct<const moe::net::Vec3 *>(VT_VEL);
  }
  const moe::net::Vec3 *head() const {
    return GetStruct<const moe::net::Vec3 *>(VT_HEAD);
  }
  moe::net::PlayerMotionState motionState() const {
    return static_cast<moe::net::PlayerMotionState>(GetField<int8_t>(VT_MOTIONSTATE, 0));
  }
  moe::net::Weapon weapon() const {
    return static_cast<moe::net::Weapon>(GetField<int8_t>(VT_WEAPON, 0));
  }
  float health() const {
    return GetField<float>(VT_HEALTH, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_TEMPID, 2) &&
           VerifyField<moe::net::Vec3>(verifier, VT_POS, 4) &&
           VerifyField<moe::net::Vec3>(verifier, VT_VEL, 4) &&
           VerifyField<moe::net::Vec3>(verifier, VT_HEAD, 4) &&
           VerifyField<int8_t>(verifier, VT_MOTIONSTATE, 1) &&
           VerifyField<int8_t>(verifier, VT_WEAPON, 1) &&
           VerifyField<float>(verifier, VT_HEALTH, 4) &&
           verifier.EndTable();
  }
};

struct PlayerUpdateBuilder {
  typedef PlayerUpdate Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_tempId(uint16_t tempId) {
    fbb_.AddElement<uint16_t>(PlayerUpdate::VT_TEMPID, tempId, 0);
  }
  void add_pos(const moe::net::Vec3 *pos) {
    fbb_.AddStruct(PlayerUpdate::VT_POS, pos);
  }
  void add_vel(const moe::net::Vec3 *vel) {
    fbb_.AddStruct(PlayerUpdate::VT_VEL, vel);
  }
  void add_head(const moe::net::Vec3 *head) {
    fbb_.AddStruct(PlayerUpdate::VT_HEAD, head);
  }
  void add_motionState(moe::net::PlayerMotionState motionState) {
    fbb_.AddElement<int8_t>(PlayerUpdate::VT_MOTIONSTATE, static_cast<int8_t>(motionState), 0);
  }
  void add_weapon(moe::net::Weapon weapon) {
    fbb_.AddElement<int8_t>(PlayerUpdate::VT_WEAPON, static_cast<int8_t>(weapon), 0);
  }
  void add_health(float health) {
    fbb_.AddElement<float>(PlayerUpdate::VT_HEALTH, health, 0.0f);
  }
  explicit PlayerUpdateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PlayerUpdate> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PlayerUpdate>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PlayerUpdate> CreatePlayerUpdate(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t tempId = 0,
    const moe::net::Vec3 *pos = nullptr,
    const moe::net::Vec3 *vel = nullptr,
    const moe::net::Vec3 *head = nullptr,
    moe::net::PlayerMotionState motionState = moe::net::PlayerMotionState_NORMAL,
    moe::net::Weapon weapon = moe::net::Weapon_WEAPON_NONE,
    float health = 0.0f) {
  PlayerUpdateBuilder builder_(_fbb);
  builder_.add_health(health);
  builder_.add_head(head);
  builder_.add_vel(vel);
  builder_.add_pos(pos);
  builder_.add_tempId(tempId);
  builder_.add_weapon(weapon);
  builder_.add_motionState(motionState);
  return builder_.Finish();
}

struct AllPlayerUpdate FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AllPlayerUpdateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UPDATES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<moe::net::PlayerUpdate>> *updates() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<moe::net::PlayerUpdate>> *>(VT_UPDATES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_UPDATES) &&
           verifier.VerifyVector(updates()) &&
           verifier.VerifyVectorOfTables(updates()) &&
           verifier.EndTable();
  }
};

struct AllPlayerUpdateBuilder {
  typedef AllPlayerUpdate Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_updates(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<moe::net::PlayerUpdate>>> updates) {
    fbb_.AddOffset(AllPlayerUpdate::VT_UPDATES, updates);
  }
  explicit AllPlayerUpdateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AllPlayerUpdate> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AllPlayerUpdate>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AllPlayerUpdate> CreateAllPlayerUpdate(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<moe::net::PlayerUpdate>>> updates = 0) {
  AllPlayerUpdateBuilder builder_(_fbb);
  builder_.add_updates(updates);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AllPlayerUpdate> CreateAllPlayerUpdateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<moe::net::PlayerUpdate>> *updates = nullptr) {
  auto updates__ = updates ? _fbb.CreateVector<::flatbuffers::Offset<moe::net::PlayerUpdate>>(*updates) : 0;
  return moe::net::CreateAllPlayerUpdate(
      _fbb,
      updates__);
}

inline const moe::net::AllPlayerUpdate *GetAllPlayerUpdate(const void *buf) {
  return ::flatbuffers::GetRoot<moe::net::AllPlayerUpdate>(buf);
}

inline const moe::net::AllPlayerUpdate *GetSizePrefixedAllPlayerUpdate(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<moe::net::AllPlayerUpdate>(buf);
}

inline bool VerifyAllPlayerUpdateBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<moe::net::AllPlayerUpdate>(nullptr);
}

inline bool VerifySizePrefixedAllPlayerUpdateBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<moe::net::AllPlayerUpdate>(nullptr);
}

inline void FinishAllPlayerUpdateBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<moe::net::AllPlayerUpdate> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedAllPlayerUpdateBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<moe::net::AllPlayerUpdate> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace net
}  // namespace moe

#endif  // FLATBUFFERS_GENERATED_PLAYERUPDATE_MOE_NET_H_
