// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PLAYERINFO_MOE_NET_H_
#define FLATBUFFERS_GENERATED_PLAYERINFO_MOE_NET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "PlayerTeam_generated.h"

namespace moe {
namespace net {

struct PlayerInfo;
struct PlayerInfoBuilder;

struct AllPlayerInfo;
struct AllPlayerInfoBuilder;

struct PlayerInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PlayerInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UUID = 4,
    VT_NAME = 6,
    VT_TEMPID = 8,
    VT_TEAM = 10
  };
  const ::flatbuffers::String *uuid() const {
    return GetPointer<const ::flatbuffers::String *>(VT_UUID);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  uint16_t tempId() const {
    return GetField<uint16_t>(VT_TEMPID, 0);
  }
  moe::net::PlayerTeam team() const {
    return static_cast<moe::net::PlayerTeam>(GetField<int8_t>(VT_TEAM, 0));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_UUID) &&
           verifier.VerifyString(uuid()) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint16_t>(verifier, VT_TEMPID, 2) &&
           VerifyField<int8_t>(verifier, VT_TEAM, 1) &&
           verifier.EndTable();
  }
};

struct PlayerInfoBuilder {
  typedef PlayerInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_uuid(::flatbuffers::Offset<::flatbuffers::String> uuid) {
    fbb_.AddOffset(PlayerInfo::VT_UUID, uuid);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(PlayerInfo::VT_NAME, name);
  }
  void add_tempId(uint16_t tempId) {
    fbb_.AddElement<uint16_t>(PlayerInfo::VT_TEMPID, tempId, 0);
  }
  void add_team(moe::net::PlayerTeam team) {
    fbb_.AddElement<int8_t>(PlayerInfo::VT_TEAM, static_cast<int8_t>(team), 0);
  }
  explicit PlayerInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PlayerInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PlayerInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PlayerInfo> CreatePlayerInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> uuid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    uint16_t tempId = 0,
    moe::net::PlayerTeam team = moe::net::PlayerTeam_TEAM_NONE) {
  PlayerInfoBuilder builder_(_fbb);
  builder_.add_name(name);
  builder_.add_uuid(uuid);
  builder_.add_tempId(tempId);
  builder_.add_team(team);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PlayerInfo> CreatePlayerInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *uuid = nullptr,
    const char *name = nullptr,
    uint16_t tempId = 0,
    moe::net::PlayerTeam team = moe::net::PlayerTeam_TEAM_NONE) {
  auto uuid__ = uuid ? _fbb.CreateString(uuid) : 0;
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return moe::net::CreatePlayerInfo(
      _fbb,
      uuid__,
      name__,
      tempId,
      team);
}

struct AllPlayerInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AllPlayerInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PLAYERS = 4,
    VT_WHOAMI = 6
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<moe::net::PlayerInfo>> *players() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<moe::net::PlayerInfo>> *>(VT_PLAYERS);
  }
  const moe::net::PlayerInfo *whoami() const {
    return GetPointer<const moe::net::PlayerInfo *>(VT_WHOAMI);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PLAYERS) &&
           verifier.VerifyVector(players()) &&
           verifier.VerifyVectorOfTables(players()) &&
           VerifyOffset(verifier, VT_WHOAMI) &&
           verifier.VerifyTable(whoami()) &&
           verifier.EndTable();
  }
};

struct AllPlayerInfoBuilder {
  typedef AllPlayerInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_players(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<moe::net::PlayerInfo>>> players) {
    fbb_.AddOffset(AllPlayerInfo::VT_PLAYERS, players);
  }
  void add_whoami(::flatbuffers::Offset<moe::net::PlayerInfo> whoami) {
    fbb_.AddOffset(AllPlayerInfo::VT_WHOAMI, whoami);
  }
  explicit AllPlayerInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AllPlayerInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AllPlayerInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AllPlayerInfo> CreateAllPlayerInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<moe::net::PlayerInfo>>> players = 0,
    ::flatbuffers::Offset<moe::net::PlayerInfo> whoami = 0) {
  AllPlayerInfoBuilder builder_(_fbb);
  builder_.add_whoami(whoami);
  builder_.add_players(players);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AllPlayerInfo> CreateAllPlayerInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<moe::net::PlayerInfo>> *players = nullptr,
    ::flatbuffers::Offset<moe::net::PlayerInfo> whoami = 0) {
  auto players__ = players ? _fbb.CreateVector<::flatbuffers::Offset<moe::net::PlayerInfo>>(*players) : 0;
  return moe::net::CreateAllPlayerInfo(
      _fbb,
      players__,
      whoami);
}

inline const moe::net::AllPlayerInfo *GetAllPlayerInfo(const void *buf) {
  return ::flatbuffers::GetRoot<moe::net::AllPlayerInfo>(buf);
}

inline const moe::net::AllPlayerInfo *GetSizePrefixedAllPlayerInfo(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<moe::net::AllPlayerInfo>(buf);
}

inline bool VerifyAllPlayerInfoBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<moe::net::AllPlayerInfo>(nullptr);
}

inline bool VerifySizePrefixedAllPlayerInfoBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<moe::net::AllPlayerInfo>(nullptr);
}

inline void FinishAllPlayerInfoBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<moe::net::AllPlayerInfo> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedAllPlayerInfoBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<moe::net::AllPlayerInfo> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace net
}  // namespace moe

#endif  // FLATBUFFERS_GENERATED_PLAYERINFO_MOE_NET_H_
