// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RECEIVECONNECTIONPACKET_MYU_NET_H_
#define FLATBUFFERS_GENERATED_RECEIVECONNECTIONPACKET_MYU_NET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace myu {
namespace net {

struct PlayerInfo;
struct PlayerInfoBuilder;

struct PlayerInfo FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PlayerInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PLAYER_UUID = 4
  };
  const ::flatbuffers::String *player_uuid() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PLAYER_UUID);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PLAYER_UUID) &&
           verifier.VerifyString(player_uuid()) &&
           verifier.EndTable();
  }
};

struct PlayerInfoBuilder {
  typedef PlayerInfo Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_player_uuid(::flatbuffers::Offset<::flatbuffers::String> player_uuid) {
    fbb_.AddOffset(PlayerInfo::VT_PLAYER_UUID, player_uuid);
  }
  explicit PlayerInfoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PlayerInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PlayerInfo>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PlayerInfo> CreatePlayerInfo(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> player_uuid = 0) {
  PlayerInfoBuilder builder_(_fbb);
  builder_.add_player_uuid(player_uuid);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PlayerInfo> CreatePlayerInfoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *player_uuid = nullptr) {
  auto player_uuid__ = player_uuid ? _fbb.CreateString(player_uuid) : 0;
  return myu::net::CreatePlayerInfo(
      _fbb,
      player_uuid__);
}

inline const myu::net::PlayerInfo *GetPlayerInfo(const void *buf) {
  return ::flatbuffers::GetRoot<myu::net::PlayerInfo>(buf);
}

inline const myu::net::PlayerInfo *GetSizePrefixedPlayerInfo(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<myu::net::PlayerInfo>(buf);
}

inline bool VerifyPlayerInfoBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<myu::net::PlayerInfo>(nullptr);
}

inline bool VerifySizePrefixedPlayerInfoBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<myu::net::PlayerInfo>(nullptr);
}

inline void FinishPlayerInfoBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<myu::net::PlayerInfo> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPlayerInfoBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<myu::net::PlayerInfo> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace net
}  // namespace myu

#endif  // FLATBUFFERS_GENERATED_RECEIVECONNECTIONPACKET_MYU_NET_H_
