// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_WEAPON_MOE_NET_H_
#define FLATBUFFERS_GENERATED_WEAPON_MOE_NET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace moe {
namespace net {

enum Weapon : int8_t {
  Weapon_WEAPON_NONE = 0,
  Weapon_GLOCK = 1,
  Weapon_USP = 2,
  Weapon_DEAGLE = 3,
  Weapon_AK47 = 4,
  Weapon_M4A1 = 5,
  Weapon_MIN = Weapon_WEAPON_NONE,
  Weapon_MAX = Weapon_M4A1
};

inline const Weapon (&EnumValuesWeapon())[6] {
  static const Weapon values[] = {
    Weapon_WEAPON_NONE,
    Weapon_GLOCK,
    Weapon_USP,
    Weapon_DEAGLE,
    Weapon_AK47,
    Weapon_M4A1
  };
  return values;
}

inline const char * const *EnumNamesWeapon() {
  static const char * const names[7] = {
    "WEAPON_NONE",
    "GLOCK",
    "USP",
    "DEAGLE",
    "AK47",
    "M4A1",
    nullptr
  };
  return names;
}

inline const char *EnumNameWeapon(Weapon e) {
  if (::flatbuffers::IsOutRange(e, Weapon_WEAPON_NONE, Weapon_M4A1)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesWeapon()[index];
}

}  // namespace net
}  // namespace moe

#endif  // FLATBUFFERS_GENERATED_WEAPON_MOE_NET_H_
